// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB071ch51HIM0hoxiuqbf3bzj9HCu2lG-Y',
    appId: '1:243056543483:web:1ba8f3a7e8259775f7525e',
    messagingSenderId: '243056543483',
    projectId: 'travellog-fd2c1',
    authDomain: 'travellog-fd2c1.firebaseapp.com',
    storageBucket: 'travellog-fd2c1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7I7zKbVrSIMi7D2aWsdx6_CNd_EfVeiA',
    appId: '1:243056543483:android:eb87f3a36fc99cc0f7525e',
    messagingSenderId: '243056543483',
    projectId: 'travellog-fd2c1',
    storageBucket: 'travellog-fd2c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLnLY3iAPuTPp4AOt6JBVEVKi2OuvgxHY',
    appId: '1:243056543483:ios:aea6d377eed289f3f7525e',
    messagingSenderId: '243056543483',
    projectId: 'travellog-fd2c1',
    storageBucket: 'travellog-fd2c1.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLnLY3iAPuTPp4AOt6JBVEVKi2OuvgxHY',
    appId: '1:243056543483:ios:aea6d377eed289f3f7525e',
    messagingSenderId: '243056543483',
    projectId: 'travellog-fd2c1',
    storageBucket: 'travellog-fd2c1.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB071ch51HIM0hoxiuqbf3bzj9HCu2lG-Y',
    appId: '1:243056543483:web:9dfac436d1290ab1f7525e',
    messagingSenderId: '243056543483',
    projectId: 'travellog-fd2c1',
    authDomain: 'travellog-fd2c1.firebaseapp.com',
    storageBucket: 'travellog-fd2c1.firebasestorage.app',
  );
}
